// Generated by purs bundle 0.13.8
var PS = {};
(function($PS) {
  // Generated by purs version 0.13.8
  "use strict";
  $PS["Main"] = $PS["Main"] || {};
  var exports = $PS["Main"];
  var hello = function (name) {
      return "Hello " + (name + " from purescript");
  };
  exports["hello"] = hello;
})(PS);
module.exports = PS["Main"];
